site_name: ComputePods Async Watch-Do tool

site_url: https://computepods.github.io/asyncWatchDo/

repo_url: https://github.com/computePods/asyncWatchDo

plugins:
  - search
  - awesome-pages
  - mermaid2
  - mkdocstrings:
      watch:
        - cpawd

theme:
  name: material
